### ISSUE TITLE
Where is version 0.3.1 on GitHub?

### ISSUE THREAD

**Issue by SuperSandro2000** [rhgrant10/ndjson#7]
### Description

I saw that PyPi.org has a version 0.3.1 which I can't find on GitHub.

### What I Did

Visited https://pypi.org/project/ndjson/#history

**Comment by rhgrant10** [comment]
hey @SuperSandro2000, thanks for letting me know. I found I have the commits locally here on my laptop still... looks like I committed, published, and simply forgot to push. anyway, I just pushed them up along with the v0.3.1 tag.
